FROM lsiobase/ffmpeg:arm32v7-bin as binstage
FROM lsiobase/alpine:arm32v7-3.9

# Add files from binstage
COPY --from=binstage / /

# set version label
ARG BUILD_DATE
ARG VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="thelamer"

RUN \
 echo "**** install packages ****" && \
 apk add --no-cache \
	expat \
	libgomp \
	libpng \
	libstdc++ \
	libxext \
	libxml2 \
	v4l-utils-libs

ENTRYPOINT ["/usr/local/bin/ffmpeg"]
