#!/usr/bin/with-contenv bash

# Make log output for dev
mkdir -p /applogs
chown -R abc:abc /applogs

# Run App in development mode
cd /app/ffmpeg-web
exec \
  s6-setuidgid abc \
    watchmedo auto-restart \
      -d . \
      -p './server.py' \
      -- python3 server.py \
      >> /applogs/applog.txt 2>&1
