#!/usr/bin/with-contenv bash

# Run App in development mode
cd /app/ffmpeg-web
exec \
  s6-setuidgid abc \
    watchmedo auto-restart \
      -d . \
      -p './server.py' \
      -- python3 server.py
